/*
 * Proyecto de Redes I
 */
package proyectoderedes.i;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;

/**
 *
 * Por: Vanessa Cruz
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Constructor de la interfaz
     */
    public Interfaz() throws LineUnavailableException {
        initComponents();
        Receptor R = new Receptor(chatbox); //si hay algo que ha sido recibido lo muestra
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenida = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        NiñoPc = new javax.swing.JLabel();
        ImagenCorreo = new javax.swing.JLabel();
        ChatBox = new javax.swing.JScrollPane();
        chatbox = new javax.swing.JTextArea();
        ChatEmi = new javax.swing.JScrollPane();
        chatemi = new javax.swing.JTextArea();
        FondoColores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenida.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        Bienvenida.setForeground(new java.awt.Color(240, 240, 240));
        Bienvenida.setText("¡Bienvenidos al Chat!");
        getContentPane().add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 360, 70));

        jButton2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 120, 40));

        NiñoPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoderedes/i/chico_png_by__vickuchatutorials_by_vickuchatutorials-d63phm8.png"))); // NOI18N
        NiñoPc.setText("jLabel3");
        getContentPane().add(NiñoPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 330, 320));

        ImagenCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoderedes/i/27936-200.png"))); // NOI18N
        ImagenCorreo.setText("jLabel5");
        getContentPane().add(ImagenCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -50, 200, 150));

        chatbox.setColumns(20);
        chatbox.setRows(5);
        ChatBox.setViewportView(chatbox);

        getContentPane().add(ChatBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 260, 290));

        chatemi.setColumns(20);
        chatemi.setRows(5);
        ChatEmi.setViewportView(chatemi);

        getContentPane().add(ChatEmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 250, 290));

        FondoColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoderedes/i/fondos-para-whatsapp-de-colores2.jpg"))); // NOI18N
        FondoColores.setText("jLabel1");
        getContentPane().add(FondoColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Cuando precionan "ENVIAR" con el mouse*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (chatemi.getText().length() < 1) { //Si NO han escrito nada no envían nada
            } else if (chatemi.getText().equals(".clear")) {
                chatbox.setText("Ventana limpia.\n");
                chatemi.setText("");
            } else {
                chatbox.append("MENSAJE NUEVO: " + chatemi.getText() + "\n");
             try {
                 //Aquí se envía la cadena a transmitir
                 new Emisor( chatemi.getText() );
             } catch (LineUnavailableException ex) {
                 Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
             }
                chatemi.setText("");
            }
            chatemi.requestFocusInWindow();
    }//GEN-LAST:event_jButton2ActionPerformed
        /*Cuando precionan "ENTER" con el teclado*/
    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (chatemi.getText().length() < 1) {  //Si NO han escrito nada no envían nada
                } else if (chatemi.getText().equals(".clear")) {
                    chatbox.setText("Ventana limpia.\n");
                    chatemi.setText("");
                } else {
                    chatbox.append("MENSAJE NUEVO:  " + chatemi.getText() + "\n");
                    try {
                        //Aquí se envía la cadena a transmitir
                        new Emisor(chatbox.getText());
                    } catch (LineUnavailableException ex) {
                        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    chatbox.setText("");
                }
                chatemi.requestFocusInWindow();
            }
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * Principal
     */
    public static void main(String args[])throws LineUnavailableException {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*RUN */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Interfaz().setVisible(true);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JScrollPane ChatBox;
    private javax.swing.JScrollPane ChatEmi;
    private javax.swing.JLabel FondoColores;
    private javax.swing.JLabel ImagenCorreo;
    private javax.swing.JLabel NiñoPc;
    private javax.swing.JTextArea chatbox;
    private javax.swing.JTextArea chatemi;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
